name: odoo_timers
description: Application for managing projects, tasks and timers.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  intl: ^0.18.0
  rxdart: ^0.27.7

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
